### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by dedsecriseing** [WayzDev/Kage#11]
i get this error

┏ Electron -------------------

  /root/Kage/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
  
┗ ----------------------------

**Comment by dedsecriseing** [comment]
ok so i solved that error but now when it launches i get this on the main screen

Html Webpack Plugin:
  ReferenceError: process is not defined
  
  - index.ejs:11 eval
    [.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:11:2
  
  - index.ejs:16 module.exports
    [.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:16:3
  
  - index.js:284 
    [Kage]/[html-webpack-plugin]/index.js:284:18
  
  - runMicrotasks
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5

**Comment by harshraj6982** [comment]
I think you are getting some vulnerabilities in npm. 
Try npm install once again and check wheather you have some vulnerability or not.

**Comment by Zerx0r** [comment]
Will close the issue if any help needed you may re-open the issue
