### ISSUE TITLE
Suggest: Add more Options For Job (i.e. autoloadstdapi, autoverifysession, etc...)

### ISSUE THREAD

**Issue by Techno-Fox** [WayzDev/Kage#12]
Hello I've notice that the Jobs creater has only two options (EnableContextEndcoding and ExitOnSession). However there are other options that are very useful. I've worked with the metasploit team to detect ways to bypass windows defender. I've found (and reported it to them) that windows defender can be bypassed using the EnableStageEncoding -> true, autoloadstdapi -> false, autoverifysession -> false). Could these options be added.

P.S. I love the idea you have here. Would help but I don't know anything about front end creation. (Is there anything with python and electron).

**Comment by Zerx0r** [comment]
Hi there, sorry for the late replay that is a pretty cool thing to add, I have some plans for 2020 to update Kage and add more metasploit features, thank you for your feedback.

for python and electron I think it can be done by making python as a proxy server that talks with metasploit RPC which will enable electron to communicate with the python program through HTTP(S).
