### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by harshraj6982** [WayzDev/Kage#13]
I am getting this error after running npm install

npm WARN lifecycle kage@0.1.1-beta~postinstall: cannot run in wd kage@0.1.1-beta npm run lint:fix (wd=/root/Kage)
npm WARN kage@0.1.1-beta No repository field.

audited 14776 packages in 18.583s

29 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by Zerx0r** [comment]
the developer of [electron-vue](https://github.com/SimulatedGREG/electron-vue) recommends the `yarn` as package manager instead of `npm`
try use [yarn](https://legacy.yarnpkg.com/lang/en/docs/install).

**Comment by harshraj6982** [comment]
root@kali:~/Kage# yarn
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.


Bro after running yarn it is giving me error like this

**Comment by Zerx0r** [comment]
Check this link up:

https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365

**Comment by harshraj6982** [comment]
After running yarn

root@kali:~/Kage# yarn
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning url-loader@1.1.2: Invalid bin field for "url-loader".
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ npm run lint:fix
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1580152648890-0.13598594857824042/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> kage@0.1.1-beta lint:fix /root/Kage
> eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix src

Done in 115.36s.


After running yarn run dev

root@kali:~/Kage# yarn run dev
yarn run v1.21.1
$ node .electron-vue/dev-runner.js
         ___                      __                                                                
   __   /\_ \       __     ___   /\ \__    _ __    ___     ___              __  __  __  __     __   
 / ,.`\ \//\ \    / ,.`\  /'___\ \ \ ,_\  /\` __\ / __`\ /' _ `\   _______ /\ \/\ \/\ \/\ \  / ,.`\ 
/\  __/   \_\ \_ /\  __/ /\ \__/  \ \ \/  \ \ \/ /\ \_\ \/\ \/\ \ /\______\\ \ \/ |\ \ \_\ \/\  __/ 
\ \____\  /\____\\ \____\\ \____\  \ \ \_  \ \_\ \ \____/\ \_\ \_\\/______/ \ \___/ \ \____/\ \____\
 \/____/  \/____/ \/____/ \/____/   \ \__\  \/_/  \/___/  \/_/\/_/           \/__/   \/___/  \/____/
                                     \/__/                                                          
  getting ready...

┏ Main Process ---------------

  compiling...

┗ ----------------------------

┏ Renderer Process -----------

  Hash: b13eb67982aea3ab4e00
  Version: webpack 4.39.2
  Time: 17786ms
  Built at: 28/01/2020 12:48:27 am
                            Asset       Size    Chunks             Chunk Names
   fonts/element-icons--fonts.ttf   54.6 KiB            [emitted]  
  fonts/element-icons--fonts.woff   27.5 KiB            [emitted]  
                       index.html  450 bytes            [emitted]  
                      renderer.js   7.63 MiB  renderer  [emitted]  renderer
  Entrypoint renderer = renderer.js
  [1] multi (webpack)-dev-server/client?http://localhost ./.electron-vue/dev-client ./src/renderer/main.js 52 bytes {renderer} [built]
  [./.electron-vue/dev-client.js] 731 bytes {renderer} [built]
  [./node_modules/element-ui/lib/element-ui.common.js] 1.09 MiB {renderer} [built]
  [./node_modules/element-ui/lib/locale/lang/en.js] 2.58 KiB {renderer} [built]
  [./node_modules/element-ui/lib/theme-chalk/index.css] 934 bytes {renderer} [built]
  [./node_modules/strip-ansi/index.js] 161 bytes {renderer} [built]
  [./node_modules/vue/dist/vue.esm.js] 318 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/index.js?http://localhost] (webpack)-dev-server/client?http://localhost 4.29 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.85 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {renderer} [built]
  [./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {renderer} [built]
  [./src/renderer/main.js] 1.12 KiB {renderer} [built]
      + 290 hidden modules
  
  ERROR in Template execution failed: ReferenceError: process is not defined
  
  ERROR in   ReferenceError: process is not defined
    
    - index.ejs:11 eval
      [.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:11:2
    
    - index.ejs:16 module.exports
      [.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:16:3
    
    - index.js:284 
      [Kage]/[html-webpack-plugin]/index.js:284:18
    
    - runMicrotasks
    
    - task_queues.js:97 processTicksAndRejections
      internal/process/task_queues.js:97:5
    
  
  Child html-webpack-plugin for "index.html":
           Asset      Size  Chunks  Chunk Names
      index.html  1.38 MiB       0  
      Entrypoint undefined = index.html
      [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs] 1.22 KiB {0} [built]
      [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
      [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]

┗ ----------------------------

┏ Main Process ---------------

  Hash: b14775061d9a377cd339
  Version: webpack 4.39.2
  Time: 18337ms
  Built at: 28/01/2020 12:48:28 am
    Asset     Size  Chunks             Chunk Names
  main.js  217 KiB    main  [emitted]  main
  Entrypoint main = main.js
  [0] multi ./src/main/index.dev.js ./src/main/index.js 40 bytes {main} [built]
  [./node_modules/electron-debug sync recursive] ./node_modules/electron-debug sync 160 bytes {main} [built]
  [./node_modules/electron-debug/index.js] 2.46 KiB {main} [built]
  [./node_modules/electron-devtools-installer/dist/downloadChromeExtension.js] 2.26 KiB {main} [built]
  [./node_modules/electron-devtools-installer/dist/index.js] 5.02 KiB {main} [built]
  [./node_modules/electron-devtools-installer/dist/utils.js] 1.88 KiB {main} [built]
  [./node_modules/electron-is-dev/index.js] 256 bytes {main} [built]
  [./node_modules/electron-localshortcut/index.js] 8.16 KiB {main} [built]
  [./node_modules/semver/semver.js] 37.9 KiB {main} [built]
  [./src/main/index.dev.js] 364 bytes {main} [built]
  [./src/main/index.js] 1.34 KiB {main} [built]
  [./src/renderer/store/index.js] 294 bytes {main} [built]
  [./src/renderer/store/modules/index.js] 238 bytes {main} [built]
  [electron] external "electron" 42 bytes {main} [built]
  [fs] external "fs" 42 bytes {main} [built]
      + 40 hidden modules
  
  WARNING in ./node_modules/electron-debug/index.js 81:45-58
  Critical dependency: the request of a dependency is an expression
   @ ./src/main/index.dev.js
   @ multi ./src/main/index.dev.js ./src/main/index.js
  
  WARNING in ./node_modules/electron-debug/index.js 84:85-106
  Critical dependency: the request of a dependency is an expression
   @ ./src/main/index.dev.js
   @ multi ./src/main/index.dev.js ./src/main/index.js

┗ ----------------------------

┏ Electron -------------------

  Debugger listening on ws://127.0.0.1:5858/6679ba05-3a29-456a-8612-a69571288bae
  For help see https://nodejs.org/en/docs/inspector
  
┗ ----------------------------

**Comment by Zerx0r** [comment]
Thank you for opening this issue, I am fixing it now, I will push the changes once it is fixed.

**Comment by Zerx0r** [comment]
fixed the issue you can use Kage now :),
