### ISSUE TITLE
Msf server is not starting

### ISSUE THREAD

**Issue by Ranjithkumar567** [WayzDev/Kage#18]
Database error ?         
'msfdb' is not recognized as an internal or external command,
operable program or batch file.

**Comment by roshanleharwani** [comment]
you can try : sudo ./Kage.0.1.1-beta_linux.AppImage
after downloading the binary file of this tool

**Comment by Zerx0r** [comment]
@Ranjithkumar567 same [issue](https://github.com/Zerx0r/Kage/issues/19#issuecomment-685896954)
