### ISSUE TITLE
msfdb error

### ISSUE THREAD

**Issue by shariat1** [WayzDev/Kage#19]
I am useing windows 10..install it without kali linux.. When start server then show error...

Error: 'msfdb' is not recognized as an internal or external command.

But metasploit already install my System.

**Comment by Zerx0r** [comment]
You need to include msfdb in windows environment path, you might find the answer [here](https://stackoverflow.com/questions/44272416/how-to-add-a-folder-to-path-environment-variable-in-windows-10-with-screensho) and make sure msfdb is installed in your machine
