### ISSUE TITLE
sudo ./Kage.0.1.1-beta_linux.AppImage: 1: Syntax error: ")" unexpected

### ISSUE THREAD

**Issue by pulpy3** [WayzDev/Kage#20]
Hi Bro, when executing the command - sudo ./Kage.0.1.1-beta_linux.AppImage, on Kali Linux 32-Bit, an error message is displayed - sudo ./Kage.0.1.1-beta_linux.AppImage: 1: Syntax error: ")" unexpected. Please add your program with support for Linux 32-Bit system.

Sincerely, Pulpy3.
Have a nice day.

**Comment by ghost** [comment]
type: `chmod +x Kage AppImage`  and  again run

**Comment by pulpy3** [comment]
> type: `chmod +x Kage AppImage` and again run

Thanks for the help, but before starting Kage, I ran this command. The problem is that Kage does not start on Linux 32-Bit system. On Linux 64-Bit system, Kage starts without errors and works fine. Please add Kage with support for Linux 32-Bit system.

**Comment by Zerx0r** [comment]
@pulpy3 if you want to get 32-bit support clone the project and build it in your environment [here is the steps](https://github.com/Zerx0r/Kage#for-developers)
