### ISSUE TITLE
Please can you solve the path were it save 

### ISSUE THREAD

**Issue by dinkadereje** [WayzDev/Kage#26]
Please can you solve the path were it save  its saving on /root/kage

**Comment by Zerx0r** [comment]
You can clone the project[Kage] and edit the path after that make your build 😄
[Edit here for screenshot](https://github.com/Zerx0r/Kage/blob/8936de3d6d976b49fbfbf20d92fce1f05112e1e3/src/renderer/components/sessionView/Workspace.vue#L554) 

If you want to change path for all downloads search for `this.$electron.remote.app.getPath('home')` in the workspace.vue and edit your path.
