### ISSUE TITLE
NETWORK ERROR

### ISSUE THREAD

**Issue by naga9989** [WayzDev/Kage#28]

**Comment by Ali83128** [comment]
AoA, Hey I had this same problem.I'm talking about some port error that says check if msfrpcd running something like that Here How I fixed it
First of all, make sure your kali is updated.That's How I make it worked I updated kali by using commands such as
`apt-get update && apt-get upgrade && apt-get dist-upgrade`
After this open your Kage framework by cmd  with sudo

After Updating everything You just need to open msfconsole in cmd by typing 
`msfconsole`

After MSFCONSOLE is activated type 
`load msfrpc`  
It will give you credentials 
Type that username and password in kage if error still occurs  keep on changing credentials again and again by `load msfrpc` command  until You login back in the server of Kage.
