### ISSUE TITLE
Can not install on Kali

### ISSUE THREAD

**Issue by ghost** [WayzDev/Kage#3]
Followed steps here...get the following error after npm run dev

https://www.hackingarticles.in/kage-graphical-user-interface-for-metasploit/

/Kage/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

**Comment by Zerx0r** [comment]
you have to install libgconf-2.so.4, use this command:

`apt-get install libgconf-2-4`

**Comment by WayzDev** [comment]
> Followed steps here...get the following error after npm run dev
> 
> https://www.hackingarticles.in/kage-graphical-user-interface-for-metasploit/
> 
> /Kage/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
