### ISSUE TITLE
Network error & port issue

### ISSUE THREAD

**Issue by prince672** [WayzDev/Kage#30]
When I am trying to connect with msf it's showing me .." Network error, pls check if msfrpcd is is running and on which protocol, if all fine then double check host:port"

The default Host and Port is 127.0.0.1:55552
And I was try to connect manually with data base with using CLI msf console of loading msfrpcd

But It's still showing me that same error

**Comment by Ali83128** [comment]
AoA, Hey I had this same problem. Here How I fixed it
First of all, make sure your kali is updated.That's How I make it worked I updated kali by using commands such as
`apt-get update && apt-get upgrade && apt-get dist-upgrade`
After this open your Kage framework by cmd  with sudo

After Updating everything You just need to open msfconsole in cmd by typing 
`msfconsole`

After MSFCONSOLE is activated type 
`load msfrpc`  
It will give you credentials 
Type that username and password in kage if error still occurs  keep on changing credentials again and again by `load msfrpc` command  until You login back in the server of Kage.

**Comment by Zerx0r** [comment]
@Ali83128 Thank you for contributing

**Comment by Azureuser-m** [comment]
> AoA, Hey I had this same problem. Here How I fixed it
> First of all, make sure your kali is updated.That's How I make it worked I updated kali by using commands such as
> `apt-get update && apt-get upgrade && apt-get dist-upgrade`
> After this open your Kage framework by cmd with sudo
> 
> After Updating everything You just need to open msfconsole in cmd by typing
> `msfconsole`
> 
> After MSFCONSOLE is activated type
> `load msfrpc`
> It will give you credentials
> Type that username and password in kage if error still occurs keep on changing credentials again and again by `load msfrpc` command until You login back in the server of Kage.

I tried that but got **Failed to load plugin from /usr/share/metasploit-framework/plugins/msfrpc: cannot load such file -- /usr/share/metasploit-framework/plugins/msfrpc**

@Zerx0r

**Comment by Zerx0r** [comment]
Sorry I miss-typed
`load msgrpc`
Output example:
`[*] MSGRPC Service: 127.0.0.1:55552
[*] MSGRPC Username: msf
[*] MSGRPC Password: abc123
[*] Successfully loaded plugin: msgrpc`

**Comment by prince672** [comment]
Thanks for helping me out with this issue
