### ISSUE TITLE
MACOS Build

### ISSUE THREAD

**Issue by rmsferreira** [WayzDev/Kage#31]
HI, first of all thanks for the great job.

Now I need to know if is possible to build the app for run on MacOS.

Thanks.

**Comment by necrose99** [comment]
https://github.com/Zerx0r/Kage/issues/21 

i mentioned how to do so , here.  however updating package.json to roll these...

**Comment by Zerx0r** [comment]
@necrose99 Thank you for showing the way!

@rmsferreira  if you follow the following steps you will get MacOS build for kage [Here](https://github.com/Zerx0r/Kage#for-developers)
`yarn run build -m` -m for macos
