### ISSUE TITLE
I'M not sure what to ask but it say's cannot find module 'electron' & 'cfont'

### ISSUE THREAD

**Issue by GitLuckyStrike** [WayzDev/Kage#38]
There is some details in the picture 

![Screenshot 1](https://user-images.githubusercontent.com/75558734/108816280-d186da80-75ad-11eb-8b51-a08d3d38842c.png)

and also tried to run 
`npm run build` 
same err as well with another module

![Screenshot 2](https://user-images.githubusercontent.com/75558734/108816315-dfd4f680-75ad-11eb-9718-99cf3a7d1eac.png)

what am i missing ! what i've done wrong i followed the steps correctly

**Comment by Zerx0r** [comment]
Try to run `npm install` first then run `npm run dev/build`

**Comment by GitLuckyStrike** [comment]
You I didn't install it ! How am I suppose to run the command, the problems it says missed module

**Comment by GitLuckyStrike** [comment]
Ofc I did that nothing changed.

**Comment by Zerx0r** [comment]
> Ofc I did that nothing changed.

Any error while running `npm install` ?

**Comment by eZh3lp** [comment]
> There is some details in the picture
> 
> ![Screenshot 1](https://user-images.githubusercontent.com/75558734/108816280-d186da80-75ad-11eb-8b51-a08d3d38842c.png)
> 
> and also tried to run
> `npm run build`
> same err as well with another module
> 
> ![Screenshot 2](https://user-images.githubusercontent.com/75558734/108816315-dfd4f680-75ad-11eb-9718-99cf3a7d1eac.png)
> 
> what am i missing ! what i've done wrong i followed the steps correctly

I replicated the issue in Kali.
Since yarn is recommended I decided to try it with yarn and it did worked.

Warning: I have first used apt install yarn which installed a wrong package. 

The steps to get it running in Kali are:

- git clone https://github.com/WayzDev/Kage.git
- cd Kage
- (sudo) apt install yarnpkg
- yarnpgk
- yarnpgk run dev
