### ISSUE TITLE
Program not installing and running

### ISSUE THREAD

**Issue by Harshpanwar1** [WayzDev/Kage#5]
When I type npm install
Then this occur
npm WARN lifecycle kage@0.1.1-beta~postinstall: cannot run in wd kage@0.1.1-beta npm run lint:fix (wd=/root/Desktop/Kage)
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN kage@0.1.1-beta No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

and when I type npm run dev

> kage@0.1.1-beta dev /root/Desktop/Kage
> node .electron-vue/dev-runner.js

         ___                      __                                       
   __   /\_ \       __     ___   /\ \__    _ __    ___     ___             
 / ,.`\ \//\ \    / ,.`\  /'___\ \ \ ,_\  /\` __\ / __`\ /' _ `\   _______ 
/\  __/   \_\ \_ /\  __/ /\ \__/  \ \ \/  \ \ \/ /\ \_\ \/\ \/\ \ /\______\
\ \____\  /\____\\ \____\\ \____\  \ \ \_  \ \_\ \ \____/\ \_\ \_\\/______/
 \/____/  \/____/ \/____/ \/____/   \ \__\  \/_/  \/___/  \/_/\/_/         
                                     \/__/                                 

                         
 __  __  __  __     __   
/\ \/\ \/\ \/\ \  / ,.`\ 
\ \ \/ |\ \ \_\ \/\  __/ 
 \ \___/ \ \____/\ \____\
  \/__/   \/___/  \/____/
                         
  getting ready...

┏ Main Process ---------------

  compiling...

┗ ----------------------------

┏ Renderer Process -----------

  Hash: c61976ef21b4ec1249ca
  Version: webpack 4.30.0
  Time: 17296ms
  Built at: 04/22/2019 8:39:27 AM
                           Asset       Size    Chunks             Chunk Names
  fonts/element-icons--fonts.ttf   10.8 KiB            [emitted]  
                      index.html  455 bytes            [emitted]  
                     renderer.js   7.01 MiB  renderer  [emitted]  renderer
  Entrypoint renderer = renderer.js
  [1] multi (webpack)-dev-server/client?http://localhost ./.electron-vue/dev-client ./src/renderer/main.js 52 bytes {renderer} [built]
  [./.electron-vue/dev-client.js] 731 bytes {renderer} [built]
  [./node_modules/element-ui/lib/element-ui.common.js] 991 KiB {renderer} [built]
  [./node_modules/element-ui/lib/locale/lang/en.js] 2.45 KiB {renderer} [built]
  [./node_modules/element-ui/lib/theme-chalk/index.css] 934 bytes {renderer} [built]
  [./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {renderer} [built]
  [./node_modules/strip-ansi/index.js] 161 bytes {renderer} [built]
  [./node_modules/vue/dist/vue.esm.js] 318 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/index.js?http://localhost] (webpack)-dev-server/client?http://localhost 8.26 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.59 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {renderer} [built]
  [./node_modules/webpack-hot-middleware/client.js?noInfo=true&reload=true] (webpack)-hot-middleware/client.js?noInfo=true&reload=true 7.59 KiB {renderer} [built]
  [./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {renderer} [built]
  [./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {renderer} [built]
  [./src/renderer/main.js] 1.12 KiB {renderer} [built]
      + 278 hidden modules
  Child html-webpack-plugin for "index.html":
           Asset      Size  Chunks  Chunk Names
      index.html  1.38 MiB       0  
      Entrypoint undefined = index.html
      [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs] 1.22 KiB {0} [built]
      [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
      [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]

┗ ----------------------------

┏ Main Process ---------------

  Hash: 6453fab402eac59a1fc3
  Version: webpack 4.30.0
  Time: 17742ms
  Built at: 04/22/2019 8:39:28 AM
    Asset     Size  Chunks             Chunk Names
  main.js  219 KiB    main  [emitted]  main
  Entrypoint main = main.js
  [0] multi ./src/main/index.dev.js ./src/main/index.js 40 bytes {main} [built]
  [./node_modules/electron-debug sync recursive] ./node_modules/electron-debug sync 160 bytes {main} [built]
  [./node_modules/electron-debug/index.js] 2.46 KiB {main} [built]
  [./node_modules/electron-devtools-installer/dist/downloadChromeExtension.js] 2.26 KiB {main} [built]
  [./node_modules/electron-devtools-installer/dist/index.js] 5.02 KiB {main} [built]
  [./node_modules/electron-devtools-installer/dist/utils.js] 1.88 KiB {main} [built]
  [./node_modules/electron-is-dev/index.js] 256 bytes {main} [built]
  [./node_modules/electron-localshortcut/index.js] 8.16 KiB {main} [built]
  [./node_modules/semver/semver.js] 37.9 KiB {main} [built]
  [./src/main/index.dev.js] 364 bytes {main} [built]
  [./src/main/index.js] 1.34 KiB {main} [built]
  [./src/renderer/store/index.js] 294 bytes {main} [built]
  [./src/renderer/store/modules/index.js] 238 bytes {main} [built]
  [electron] external "electron" 42 bytes {main} [built]
  [fs] external "fs" 42 bytes {main} [built]
      + 40 hidden modules
  
  WARNING in ./node_modules/electron-debug/index.js 81:45-58
  Critical dependency: the request of a dependency is an expression
   @ ./src/main/index.dev.js
   @ multi ./src/main/index.dev.js ./src/main/index.js
  
  WARNING in ./node_modules/electron-debug/index.js 84:85-106
  Critical dependency: the request of a dependency is an expression
   @ ./src/main/index.dev.js
   @ multi ./src/main/index.dev.js ./src/main/index.js

┗ ----------------------------

┏ Electron -------------------

  /root/Desktop/Kage/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
  
┗ ----------------------------

this occur please help me.

**Comment by Zerx0r** [comment]
you have to install libgconf-2.so.4, use this command:

`apt-get install libgconf-2-4`

And let me know if all good.

**Comment by Harshpanwar1** [comment]
Thanks that solve my problem .

**Comment by Zerx0r** [comment]
Anytime 😃

**Comment by vaibhav10107** [comment]
bash: ./Kage.0.1.1-beta_linux.AppImage: cannot execute binary file: Exec format error

please help me
