### ISSUE TITLE
Hello, how to solve [01:31m[－] [00m Error: usr/bin/msfdb must be [01;31mrun as root [00m], thank you!!❤️

### ISSUE THREAD

**Issue by woodwi** [WayzDev/Kage#51]
![0edd5633505e132bdf218faf7900122](https://user-images.githubusercontent.com/44332089/174481703-ce393c9f-70da-4d33-991d-bbc5992653c7.jpg)
![7df566cb8156a6ad886efb6e64738b7](https://user-images.githubusercontent.com/44332089/174481705-f5d162ee-f2e6-4cc6-a720-74422b361164.jpg)
![45f403414069cb4be577bc7aa286ec6](https://user-images.githubusercontent.com/44332089/174481709-31be4231-0119-4f3d-8dd0-7fd0b68c8198.jpg)

**Comment by Zerx0r** [comment]
This error related to permissions, start Kage as root (not recommended) or give to your current user a permission to start msfdb.
