### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by Oka911** [WayzDev/Kage#57]

**Comment by Zerx0r** [comment]
Make sure that metasploit is installed and added to env path.

**Comment by kdbdkhdkdjdhlf** [comment]
لو واحد عاوز يصنع لينك ملخب للاختار عاوز الاوامر

**Comment by kdbdkhdkdjdhlf** [comment]
لو واحد عاوز يصنع لينك ملخب للاختار عاوز الاوامر
